# Generated by Django 3.1.14 on 2021-12-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostcardCreatorCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=2048, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
