# Generated by Django 3.1.14 on 2021-12-12 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostcardJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('WAITING', 'Waiting'), ('ENQUEUED', 'Enqueued'), ('SENT', 'Sent')], default='CREATED', max_length=20)),
                ('send_on', models.DateTimeField(default=datetime.datetime.now)),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
