# Generated by Django 3.1.14 on 2022-01-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211221_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-is_primary', 'user')},
        ),
        migrations.AddField(
            model_name='address',
            name='display_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=20),
        ),
    ]
