# Generated by Django 3.1.14 on 2022-01-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20220108_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('display_status', '-is_primary', 'user')},
        ),
        migrations.AddField(
            model_name='postcardjob',
            name='rich_message_data',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
