version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - internal

  celery:
    build: ./
    command: celery --app=config worker --loglevel=info -B
    volumes:
      - ./:/home/app
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db
      - redis
    networks:
      - internal

  nginx:
    build: ./docker_nginx/
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
    labels:
      - "traefik.http.middlewares.mailman-redirect-secure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.mailman-redirect-secure.redirectscheme.permanent=true"
      - "traefik.http.routers.mailman-web.middlewares=mailman-redirect-secure"
      - "traefik.http.routers.mailman-web.rule=Host(`mailman.imakethings.ch`)"
      - "traefik.http.routers.mailman-web.entrypoints=web"
      - "traefik.http.routers.mailman.rule=Host(`mailman.imakethings.ch`)"
      - "traefik.http.routers.mailman.tls=true"
      - "traefik.http.routers.mailman.tls.certresolver=letsencrypt"
    networks:
      - traefik
      - internal

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - ./.env.prod
      - ./.env.prod.db
    networks:
      - internal

  redis:
    image: redis:6-alpine

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  internal:
  traefik:
    external: true
    name: proxy