version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery:
    build: ./
    command: celery --app=config worker --loglevel=info
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

  celery-beat:
    build: ./
    command: celery --app=config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  redis:
    image: redis:6-alpine

volumes:
  postgres_data: